- mpd.py
I think that the disconnect method should accept being called without raising an connection error.
Example, in the case where an user want called this method in the block ``finally``, same when any connection is alive. :smiley:
> Allow to call the method disconnect, same when any connection is alive

- examples/asyncio_example.py
- examples/summary.txt
- mpd/asyncio.py
- mpd/base.py
- mpd/tests.py
This is a new approach to asyncio support. It is functional, but bare; before continuing by addressing the following, I'd like to have the groundwork reviewed:
* Idle is supported but noidle is not; while it could be added, I think that library-managed idling is more suitable for an asyncio port.
* Command lists are not supported yet.
* Python 3.6 is required. Support down to 3.4 should be possible, but requires extensive de-sugaring. Support for 3.5 would work with moderate de-sugaring. I'd recommend not going that route and declaring the asyncio interface 3.6+ – that's about the version where async became really well usable.
The top two commits are do modify the base implementation to make more of it usable with asyncio (hello: reduce code duplication by moving a line out of a private …
> New asyncio branch

- mpd/asyncio.py
replace undefined variable `path` by `host`, which is most likely what the author intended.
> fix wrong variable name

- mpd/asyncio.py
- mpd/tests.py
The current disconnect method of  asyncio.MPDClient does not close the writing transport. A warning for this is issued when running the python3 interpreter with -Wdefault. As a result, the MPD server keeps alive the connection to the client unnecessarily. If this happens repeatedly, the dangling connections may cause the MPD server to reach its maximal connection limit.
> Close transport on asyncio client disconnect

- mpd/base.py
Nagle's algorithm plays badly with delayed ACK algorithm. MPD server doesn't set its socket option, so we need to fix the client side to make interactive clients more responsive.
To demonstrate the problem, consider this program which checks changed subsystems using `idle` and `noidle`:
#!/usr/bin/env python3
import mpd
import time
mpc = mpd.MPDClient()
mpc.connect('localhost', 6600)
t0 = time.time()
for i in range(50):
mpc.send_idle()
mpc.noidle()
t1 = time.time()
print(t1 - t0)
This is the write-write-read patten that suffers from the ACK delay in each iteration. With `TCP_NODELAY`, it runs 500-1000x faster.
> Create TCP socket with `TCP_NODELAY`.

- doc/topics/commands.rst
When reading the docs, I wasn't quite sure if e.g. "Displays xyz" entails that the method call itself already prints the results. I replaced "displays", "dumps" and other verbs that misleadingly sound like command executions instead of return values with "returns".
> clarify when methods return something

- mpd/base.py
This was removed in python 3.9
> No longer depend on collections.Callable

- mpd/asyncio.py
- mpd/tests.py
* asyncio: Initialize __idle_task
Otherwise, the tests fail if test_noresponse() is not skipped:
disconnect() checks whether __idle_task is None, and gets an
AttributeError if connect() never succeeded.
* tests: Add a way to allow slow tests to be run
On continuous integration systems that are not being used interactively,
it will probably take more than 5 seconds to install the
build-dependencies anyway, and usually nobody will be waiting for the
results, so we might as well run all tests - even the slow ones.
> Add a way to allow slow tests to be run

- mpd/asyncio.py
- mpd/base.py
There is an error in asyncio._parse_objects_direct when executing
commands as 'search':
UnboundLocalError: local variable 'delimiters' referenced before assignment
This error occurs because WrappedLoop does not have access to the param 'delimiters', so we have to pass it again when the instance of that class is created.
> Fix: Error with delimiters in asyncio

- doc/topics/commands.rst
- mpd/base.py
- mpd/tests.py
This PR builds upon the work done by @auchter in #111, and implements support for the `albumart` MPD command. The core work was all his; I added unit tests, documentation, and some edge case tweaks. (If needed, I'm happy to squash commits, merge these changes into the original #111 branch, or otherwise.)
Protocol documentation references as per #111:
1. https://www.musicpd.org/doc/html/protocol.html?highlight=cover#the-music-database
2. https://www.musicpd.org/doc/html/protocol.html?highlight=cover#binary
> Add support for fetching album art (with unit tests)

- README.rst
- mpd/asyncio.py
- mpd/tests.py
- setup.py
- shell.nix
- tox.ini
These changes remove a minor line of cruft that's obsolete after #134 (which this practically depends on), and add to the tests to cover the code that was questionable for possibly reintroducing the #117 bug.
Test coverage goes up from 58% to 69% for that file in the py39 tests I ran.
> asyncio: Update tests to cover more

- mpd/base.py
This allows existing projects such as sonata and beets to work with
version 2, with appropriate deprecation warnings.
---
If git master is meant to be leading to a version 3 that drops deprecated stuff, it might be more appropriate to have a 2.1.0 or 2.0.1 release from a branch with this, and then revert it on master.
> Reinstate use_unicode constructor parameter, but mark it as deprecated

- doc/topics/commands.rst
- mpd/asyncio.py
- mpd/base.py
- mpd/tests.py
The change enables solving #121 in a straightforward fashion (it should be just another two lines, but I don't have a recent mpd around to test yet), and aligns the sync and async ways of getting binary data. It's modeled around a simplified version of the command creation abstraction: Rather than passing the read lines into the decorated function (which'd then pass it on to _parse_objects or such), with binary commands a _parse_objects-ish step is concluded (by executing the lockstepped data transfer), and the final object that looks like `{"type": "image/png", binary: b"\x89PNG..."}` is passed into the callback for any final cleanup.
This depends on #139; treating them as one big PR (possibly with any further necessary discussion about the async changes in #139) here has the upside that …
> albumart: Switch to {"binary": b"..."} results

- doc/topics/commands.rst
- examples/coverart.py
- mpd/asyncio.py
- mpd/base.py
- mpd/tests.py
Based on the excellent work done in #141. Fixes #121.
This PR makes the required tweaks to account for empty responses from binary commands, as well as adding documentation and tests for `readpicture`. An example script is also provided for practical testing.
> Add readpicture command

- README.rst
002ab565f93e59c99043121f081a1cb30b7c70bb renamed this file from
PORTING.txt to PORTING.rst, while
d87113bc6559a02fa55da3cca5179defde236d7e moved PORTING.rst into the docs
tree.
Link to the rendered file instead for consistency.
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
> Update reference to porting guide

- mpd/asyncio.py
Previously a call to `disconnect()` before successfully having
connected at least once would fail with an AttributeError because
MPDClient.__wfile would not have been initialized.
Fixes: #152
**Disclaimer**
This is an educated guess and has not been verified to do anything meaningful. Though I believe it won't set your house on fire or make the situation worse than it was.
> asyncio: Initialize rfile/wfile in MPDClient constructor

- examples/asyncio_example.py
- mpd/asyncio.py
The typing was added anticipating [145], and can be removed if that's
not going anywhere; more important was documenting the variable (even
though it's internal), and making sure it's only accessed in ways that
tolerate double disconnects (eg. due to a network disconnect racing
against a user disconnect, or because something disconnects just to be
sure).
Closes: https://github.com/Mic92/python-mpd2/issues/157
[145]: https://github.com/Mic92/python-mpd2/pull/145/files
> async: Tolerate early disconnects

- doc/changes.rst
- mpd/base.py
The home-assistant mpd component requires the latest early disconnect fix in asyncio.
> Release v3.0.3

- examples/coverart.py
- examples/errorhandling.py
- mpd/__init__.py
- mpd/base.py
This allows for improved error handling based on error numbers, offsets
in a command list, command and ultimately also hands you the literal
error message.
The whole story is, that a home-assistant user came forward complainig
about the noise from `albumart` commands that returned 
> [50@0] {albumart} No file exists
for every song, that didn't have any. There is currently no clean way to
ignore specific errors, but to rely on string matching. Instead of everyone
doing that for themselves I believe a simple pattern like this might be
useful.
> Parse failure responses in CommandError exception

- mpd/asyncio.py
- mpd/tests.py
Closes https://github.com/Mic92/python-mpd2/issues/165 by turning any error during idle into idle events (after all, something *did* possibly change around, for example, the database, but the application may not be able to read the status now).
Along with tests to go with it, and some test cleanup as the idle test runs long enough that mockers start being GC'd while their clients are still around enough to send idle commands. (They always did, but the tests ran though fast enough to not cause the warnings that'd now show).
> Asyncio handle idle errors

- mpd/tests.py
- setup.py
- tox.ini
A built-in unittest.mock module is available since Python 3.3 that
is a drop-in replacement for the external mock package.  Since Python 2
is not supported, just use that and remove the dependency.
> tests: Use built-in unittest.mock instead of external mock

- README.rst
- doc/generate_command_reference.py
- doc/topics/advanced.rst
- doc/topics/commands.rst
- doc/topics/getting-started.rst
- mpd/asyncio.py
- mpd/tests.py
There are small typos in:
- README.rst
- doc/generate_command_reference.py
- doc/topics/advanced.rst
- doc/topics/commands.rst
- doc/topics/getting-started.rst
- mpd/asyncio.py
- mpd/tests.py
Fixes:
- Should read `probably` rather than `probablyy`.
- Should read `parenthese` rather than `paranthese`.
- Should read `omitting` rather than `ommiting`.
- Should read `internally` rather than `internaly`.
- Should read `incoming` rather than `incmoing`.
- Should read `configurable` rather than `configureable`.
- Should read `because` rather than `beause`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- examples/asyncio_example.py
- mpd/asyncio.py
- mpd/tests.py
This fixes https://github.com/Mic92/python-mpd2/issues/178, and changes the example to use the more modern asyncio.run idiom which should give better handling of interruptions.
The latter is only in 3.7 (while mpd2 still supports 3.6), but I think that the example doesn't need to be that strict (and 3.6 is about to lose support on the Python side anyway).
> Python 3.10 fixes

- mpd/base.py
- mpd/tests.py
Hi!
This a followup of #186. Here is the output of the example form the issue with the patched version:
```
Python 3.9.9 (main, Nov 28 2021, 10:57:04) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpd import MPDClient
>>> c=MPDClient()
>>> c.connect("localhost", 6600)
>>> c.list("album", "albumartist", "Kraftwerk", "group", "date", "group", "albumartist")
[{'albumartist': 'Kraftwerk', 'date': '1970', 'album': 'Tone Float (Unofficial)'}, {'albumartist': 'Kraftwerk', 'date': '1974', 'album': 'Autobahn'}, {'albumartist': 'Kraftwerk', 'date': '1974', 'album': 'Autobahn (2009 Der Katalog)'}, {'albumartist': 'Kraftwerk', 'date': '1975', 'album': 'Radio-Activity'}, {'albumartist': 'Kraftwerk', 'date': '1975', 'album': 'Radio-Activity (2009 …
```
> fixed multiple use of "group" in list command

- mpd/base.py
MPDClient.unmount is missing, instead MPDClient.umount is found but doesn't work as expected.
```
In [1]: from mpd import MPDClient
In [2]: client = MPDClient()
In [3]: client.connect('192.168.0.187', 6600)
In [4]: client.listmounts()
Out[4]: [{'mount': ''}, {'mount': 'foo', 'storage': 'http://192.168.0.187:9000/media'}]
In [5]: client.unmount('foo')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-034474681c24> in <module>
----> 1 client.unmount('foo')
AttributeError: 'MPDClient' object has no attribute 'unmount'
In [6]: client.umount('foo')
---------------------------------------------------------------------------
CommandError                              Traceback …
```
> fix unmount command not working

- mpd/base.py
Since protocol version 0.22.4 MPD supports the `binarylimit` command to speed up cover fetching. See: https://github.com/MusicPlayerDaemon/MPD/issues/1038 and https://github.com/MusicPlayerDaemon/MPD/commit/995aafe9cc511430bff7a7a690df70998f4bb025
This pull request enables python-mpd2 to use it.
> added binarylimit command

- mpd/asyncio.py
- mpd/base.py
The `@` prefix is an mpd convention: it is used in `mpd.conf` `bind_to_address` and by libmpdclient (and everything downstream: mpc etc...). It doesn't hurt to be more permissive and accept paths starting with the NUL byte as well, as that's the Linux socket API convention and doesn't violate mpd2's backwards compatibility anyways. 
Regarding backwards compatibility: for `mpd.base`, this should not be a breaking change: `@` is not allowed in hostnames and `connect(host)` only accepts absolute paths. However, this may be a breaking change for `mpd.asyncio` users: the current implementation of `connect(host)` only checks for presence of the path separator `/` in `host`, meaning it accepts relative paths. I purposefully did not change this behavior in order to ensure the PR remains focused …
> Implement abstract socket support

- mpd/asyncio.py
- mpd/base.py
Hello,
while experimenting with cythonizing python-mpd2, the compiler found two small issues:
* In asyncio.py, the missing import "CommandListError" is used in line 468.
* In base.py, the variable data is not available in _read_binary and value seems to be the correct one. Propably a c&p error.
Kind Regards
Michael
> missing import / wrong variable

- mpd/asyncio.py
- mpd/tests.py
When two commands were issued exactly 0.1 seconds apart, then `mpd.asyncio.MPDClient.__run` would incorrectly send an "idle" command to the server, and then attempt to parse the server's response to the second command as an "idle" response, causing errors like
```
mpd.base.ProtocolError: Expected key 'volume', got 'repeat'
```
as described by Mic92/python-mpd2#195, and hangs as described by Mic92/python-mpd2#173.
The root of the problem is that wrapping `asyncio.Queue.get` in `asyncio.wait_for` can result in a `TimeoutError` exception even when the queue is not empty, as demonstrated by the following example (tested with python 3.9.2 and 3.11.2):
```python
import asyncio
TIMEOUT = 0.1
async def get_from_queue(queue):
try:
await asyncio.wait_for(
queue.get(),
timeout=TIMEOUT
)
except …
```
> asyncio: fix race condition in command queue

- mpd/asyncio.py
Fixes #220 (see issue for details about the problem fixed here).
The fix consists in iterating over all commands still in the queue while we are running the generic exception handler, and pass each of them the exception being handled by calling their `_feed_error()` method.
With the fix, the output of the minimal script reproducing the issue is:
```
Fetching status...
Status: {'repeat': '0', 'random': '0', 'single': '0', 'consume': '0', 'partition': 'default', 'playlist': '8', 'playlistlength': '10', 'mixrampdb': '0.000000', 'state': 'stop'}
Fetching status...
Connection failure!
Done!
Exception in callback MPDClient.__idle_result(<CommandResul...ectionError()>)
handle: <Handle MPDClient.__idle_result(<CommandResul...ectionError()>)>
Traceback (most recent call last):
File …
```
> Propagate exception to all pending commands
